#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-dm-constraints
Version  : 1.2.0
Release  : 1
URL      : https://rubygems.org/downloads/dm-constraints-1.2.0.gem
Source0  : https://rubygems.org/downloads/dm-constraints-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-dm-core
BuildRequires : rubygem-dm-migrations
BuildRequires : rubygem-jeweler
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
= dm-constraints
Plugin that adds foreign key constraints to associations.
Currently supports only PostgreSQL and MySQL

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n dm-constraints-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-dm-constraints.gemspec

%build
gem build rubygem-dm-constraints.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
dm-constraints-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/dm-constraints-1.2.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Adapters/cdesc-Adapters.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Associations/ManyToMany/Relationship/cdesc-Relationship.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Associations/ManyToMany/cdesc-ManyToMany.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Associations/ManyToOne/cdesc-ManyToOne.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Associations/OneToMany/Relationship/cdesc-Relationship.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Associations/OneToMany/cdesc-OneToMany.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Associations/cdesc-Associations.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/AbstractAdapter/cdesc-AbstractAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/AbstractAdapter/constraint_exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/AbstractAdapter/create_relationship_constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/AbstractAdapter/destroy_relationship_constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/DataObjectsAdapter/SQL/cdesc-SQL.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/DataObjectsAdapter/SQL/constraint_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/DataObjectsAdapter/SQL/create_constraints_statement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/DataObjectsAdapter/SQL/destroy_constraints_statement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/DataObjectsAdapter/cdesc-DataObjectsAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/DataObjectsAdapter/constraint_exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/DataObjectsAdapter/create_relationship_constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/DataObjectsAdapter/destroy_relationship_constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/DataObjectsAdapter/valid_relationship_for_constraint%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/Extension/cdesc-Extension.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/Extension/const_added-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/Extension/constraint_extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/Extension/include_constraint_api-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/MysqlAdapter/SQL/cdesc-SQL.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/MysqlAdapter/SQL/destroy_constraints_statement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/MysqlAdapter/cdesc-MysqlAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/OracleAdapter/cdesc-OracleAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/OracleAdapter/constraint_exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/OracleAdapter/create_constraints_statement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/OracleAdapter/destroy_constraints_statement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/PostgresAdapter/cdesc-PostgresAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/SqliteAdapter/cdesc-SqliteAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/SqliteAdapter/constraint_exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/SqliteAdapter/create_relationship_constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/SqliteAdapter/destroy_relationship_constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/SqlserverAdapter/cdesc-SqlserverAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Adapters/cdesc-Adapters.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/Model/auto_migrate_constraints_down-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/Model/auto_migrate_constraints_up-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/Model/cdesc-Model.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/Relationship/ManyToOne/auto_migrate_constraints_down-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/Relationship/ManyToOne/auto_migrate_constraints_up-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/Relationship/ManyToOne/cdesc-ManyToOne.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/Relationship/auto_migrate_constraints_down-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/Relationship/auto_migrate_constraints_up-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/Relationship/cdesc-Relationship.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/SingletonMethods/auto_migrate%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/SingletonMethods/auto_migrate_constraints_down-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/SingletonMethods/auto_migrate_constraints_up-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/SingletonMethods/auto_migrate_down%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/SingletonMethods/auto_migrate_up%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/SingletonMethods/cdesc-SingletonMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Migrations/cdesc-Migrations.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Relationship/ManyToMany/assert_valid_constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Relationship/ManyToMany/cdesc-ManyToMany.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Relationship/ManyToMany/one_to_many_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Relationship/OneToMany/assert_valid_constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Relationship/OneToMany/cdesc-OneToMany.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Relationship/OneToMany/constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Relationship/OneToMany/enforce_destroy_constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Relationship/OneToMany/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Relationship/OneToMany/set_constraint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Relationship/cdesc-Relationship.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Resource/before_destroy_hook-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Resource/cdesc-Resource.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/Resource/enforce_destroy_constraints-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/Constraints/cdesc-Constraints.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/DataMapper/cdesc-DataMapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-constraints-1.2.0/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/dm-constraints.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/abstract_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/do_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/mysql_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/oracle_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/postgres_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/sqlite_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/sqlserver_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/migrations/model.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/migrations/relationship.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/migrations/singleton_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/relationship/many_to_many.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/relationship/one_to_many.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/resource.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/lib/dm-constraints.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/spec/integration/constraints_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/spec/isolated/require_after_setup_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/spec/isolated/require_before_setup_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/spec/isolated/require_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/spec/rcov.opts
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/spec/spec.opts
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/tasks/spec.rake
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/tasks/yard.rake
/usr/lib64/ruby/gems/2.2.0/gems/dm-constraints-1.2.0/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.2.0/specifications/dm-constraints-1.2.0.gemspec
