#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-dm-constraints
Version  : 1.2.0
Release  : 3
URL      : https://rubygems.org/downloads/dm-constraints-1.2.0.gem
Source0  : https://rubygems.org/downloads/dm-constraints-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-dm-core
BuildRequires : rubygem-dm-migrations
BuildRequires : rubygem-jeweler
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
= dm-constraints
Plugin that adds foreign key constraints to associations.
Currently supports only PostgreSQL and MySQL

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n dm-constraints-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-dm-constraints.gemspec

%build
gem build rubygem-dm-constraints.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
dm-constraints-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/dm-constraints-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/dm-constraints.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/abstract_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/do_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/extension.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/mysql_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/oracle_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/postgres_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/sqlite_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/adapters/sqlserver_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/migrations/model.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/migrations/relationship.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/migrations/singleton_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/relationship/many_to_many.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/relationship/one_to_many.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/data_mapper/constraints/resource.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/lib/dm-constraints.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/spec/integration/constraints_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/spec/isolated/require_after_setup_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/spec/isolated/require_before_setup_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/spec/isolated/require_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/spec/rcov.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/spec/spec.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/tasks/spec.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/tasks/yard.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-constraints-1.2.0/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.3.0/specifications/dm-constraints-1.2.0.gemspec
